use std::collections::hash_map::HashMap;

#[derive(Debug, PartialEq,Clone)]
pub enum Node{
    Integer(i64),
    Boolean(bool),
    Ident(String),
    Add(Box<Node>,Box<Node>),
    Sub(Box<Node>,Box<Node>),
    Mul(Box<Node>,Box<Node>),
    Div(Box<Node>,Box<Node>),
    Mod(Box<Node>,Box<Node>),
    Neg(Box<Node>),
    Eq(Box<Node>,Box<Node>),
    Ne(Box<Node>,Box<Node>),
    Lt(Box<Node>,Box<Node>),
    Gt(Box<Node>,Box<Node>),
    Le(Box<Node>,Box<Node>),
    Ge(Box<Node>,Box<Node>),
    And(Box<Node>,Box<Node>),
    Or(Box<Node>,Box<Node>),
    Not(Box<Node>),
    Conditional(Box<Node>,Box<Node>,Box<Node>),
    Assign(Box<Node>,Box<Node>),
    Decl(Box<Node>,Box<Node>),
    LambdaDef(Vec<Box<Node>>,Vec<(Vec<Box<Node>>,Box<Node>)>,Box<Node>),
    FuncBind(Box<Node>,Box<Node>),
    Call(Box<Node>,Vec<Box<Node>>),
    PatternDef(Vec<Box<Node>>),
    StructMatch(Box<Node>,Vec<Box<Node>>),
    ListMatch(Box<Node>,Vec<Box<Node>>),
    Block(Vec<Box<Node>>),
    ExprStmt(usize,Box<Node>),
    IfStmt(usize,Vec<(/*condition*/Box<Node>,/*if true*/Box<Node>)>),
    LoopStmt(usize,Box<Node>,Box<Node>),
    ReturnStmt(usize,Box<Node>),
    Empty()
}
